# action.yml
name: 'Syncmaven Action'
description: 'Run Syncmaven sync command. https://syncmaven.sh'
inputs:
  dir:
    description: 'Project subdirectory'
    required: false
  select:
    description: 'Syncs to run'
    required: false
  state:
    description: 'State DB location, e.g. postgres://user:password@host:port/dbname'
    required: false
  debug:
    description: 'Enable extra logging for debugging purposes'
    required: false
  full:
    description: 'If sync supports incremental mode, this option will force full refresh. Will apply to all selected syncs'
    required: false
  retry:
    description: 'Retry count on failure'
    required: false
branding:
  icon: 'refresh-cw'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
